### ISSUE TITLE
Empty headers are added to poem without hd

### ISSUE THREAD

**Issue by egli** [nlbdev/nordic-epub3-dtbook-migrator#374]
When a book contains many poems we end up with many added headings, as the `dtbook:poem` are converted to `html:section` and [`generate-missing-headlines.xsl`](https://github.com/nlbdev/nordic-epub3-dtbook-migrator/blob/master/src/main/resources/xml/xslt/generate-missing-headlines.xsl) adds empty headlines to those. What aggravates the issue is that all of those end up in the navigation.

There seem to be two possible solutions to this:

### Convert poems without a heading to `html:div` instead of `html:section`
The [mapping](http://nlbdev.github.io/nordic-epub3-dtbook-migrator/mapping.html) says that a `dtbook:poem` without a header should be converted it to a `html:div`.

But in reality it converts a `dtbook:poem` without a header to a `html:section`. This is even confirmed by [a xspec test](https://github.com/nlbdev/nordic-epub3-dtbook-migrator/blob/master/src/test/xspec/dtbook-to-epub3.xspec#L930).

If poems were `html:div` then no empty headings would be added.

### Do not add headlines to poems
This is fairly easy to achieve, just exclude poems in [`generate-missing-headlines.xsl`](https://github.com/nlbdev/nordic-epub3-dtbook-migrator/blob/master/src/main/resources/xml/xslt/generate-missing-headlines.xsl)

Which way should a solution go?

**Comment by josteinaj** [comment]
All sections should be referenced from `nav.xhtml` (I think). And while that toc could reference a section without a headline, we need some default text for the toc. It could be "Poem". Now it's "Untitled section", which is apparently also inserted as a headline in the content itself. So if we want to keep using the section element, but remove the headline, then we need to make sure that the navigation document is still valid.

According to the [Z39.98-2012 Structural Semantics Vocabulary](http://www.daisy.org/z3998/2012/vocab/structure/), a poem is a "document component", which is
"Non-structural components that occur within documents, such as letters, poems, quotations, etc.". In other words, I suppose it should be mapped to a div.

If it contains a headline title however, then it should become a structural component so that we can properly mark up the headline.

So, I'd say we should convert to div when there's no headline, and section when there's a headline.
