### ISSUE TITLE
Example of how to convert dtbook to epub3 without pipeline2

### ISSUE THREAD

**Issue by rkeiii** [nlbdev/nordic-epub3-dtbook-migrator#541]
I read in https://github.com/nlbdev/nordic-epub3-dtbook-migrator/issues/522 that it's now possible to run the dtbook to epub3 converter without the DAISY Pipeline but I couldn't find an example. Is it documented somewhere how to do this and I'm missing it? If not could someone provide one?

I tried using the calabash command line directly with the xpl scripts but I failed to find the right incantation:
```
❯ java -jar /path/to/xmlcalabash-1.5.3-110.jar -i source=/home/tmp/dtbook-to-epub/dtbook.xml -o result=/tmp/out.xml ./dtbook-to-epub3.xpl
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Error
  SXXP0003   Error reported by XML parser: Premature end of file.: Premature end of file.
```

**Comment by josteinaj** [comment]
Hi @rkeiii!

In #522 we are working on a version of the Nordic EPUB3 Validator that will run without Pipeline 2. It is mainly the documentation that remains.

It will support both the 2015-1 and 2020-1 versions of the guidelines. It will not support validation of DTBook, or any form of conversion between DTBook, HTML and EPUB.

In the future, we might work on a conversion between EPUBs following the 2015-1 guidelines and EPUBs following the 2020-1 guidelines. That would make it easier for many of us to transition from the old to the new EPUB guidelines. It is unlikely that we will include support for validation of or conversion from DTBook in the future.

I have not tried running the scripts using vanilla calabash for a long time. It might have worked up until 2020. However, in 2020, we moved much of the conversion logic from this nordic project and into the main Pipeline 2 project.

If you need to convert from DTBook, and are not restricted to using the nordic DTBook guidelines, then I recommend you try the official Pipeline 2 version. Since 2020, it is based on the conversion in the nordic validator, but is better.

If you need to convert from DTBook, and are restricted to using the nordic DTBook guidelines, then I recommend you use the last nordic validator version that is based on Pipeline 2. We will keep information on the website about how to run this version: https://nlbdev.github.io/nordic-epub3-dtbook-migrator/

**Comment by rkeiii** [comment]
@josteinaj 

I just wanted to say thank you for the response. That's very helpful. I will pursue testing with a newer version of the pipeline.
